spring:
  application:
    name: product-api
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: root
    password: root
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      #we have to specify dialect because of difference between database querying
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create


server:
  port: 8081