spring:
  application:
    name: Monolith-Demo
  datasource:
    url: jdbc:postgresql://localhost:5432/monolithdb
    username: erano
    password: 12345
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      #we have to specify dialect because of difference between database querying
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      file: Monolith-Demo/docker-compose.yml
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: beans, health
#        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

server:
  shutdown: graceful

info:
  app:
    name: MonolithApp
    description: App Built By Us
    version: 1.0.0
