spring:
  application:
    name: order-api
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    ## url: jdbc:postgresql://localhost:5432/order
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


server:
  port: 8083